<a href="https://colab.research.google.com/github/mozartMiBciBA/Data-Driven-Science-and-Engineering-ML-DySystems-and-Ctrl/blob/main/CH1_Sec1_1_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementación de código del libro "Data-Driven Science and Engineering: Machine Learning, Dynamical Systems, and Control"

Fuente1: http://databookuw.com/

Fuente2: https://www.eigensteve.com/copy-of-publications

Fuente3: http://databookuw.com/databook.pdf


In the sections below, we show how to use the SVD in python computational language

In [1]:
import numpy as np

In [2]:
X = np.random.rand(5, 3) # create random data matrix
U, S, V = np.linalg.svd(X,full_matrices=True) # full SVD
Uhat, Shat, Vhat = np.linalg.svd(X, full_matrices=False) # economy SVD

In [3]:
print("U")
print(U)
print("S")
print(S)
print("V")
print(V)

U
[[-0.27630801  0.19729792  0.4512591  -0.59739727 -0.56939365]
 [-0.54171153  0.47560222 -0.37126269  0.46539934 -0.35485012]
 [-0.48093196 -0.5591308  -0.54337232 -0.40000173  0.02867654]
 [-0.39203749 -0.54914105  0.54991959  0.48657609 -0.0747186 ]
 [-0.49519042  0.34740887  0.2467067  -0.17251747  0.73720217]]
S
[2.11185403 0.7915771  0.42181921]
V
[[-0.55614302 -0.58661045 -0.5887216 ]
 [ 0.3180227   0.50425002 -0.80286579]
 [ 0.76783234 -0.63373504 -0.09387969]]


Economy SVD

In [4]:
print("Uhat")
print(Uhat)
print("Shat")
print(Shat)
print("Vhat")
print(Vhat)

Uhat
[[-0.27630801  0.19729792  0.4512591 ]
 [-0.54171153  0.47560222 -0.37126269]
 [-0.48093196 -0.5591308  -0.54337232]
 [-0.39203749 -0.54914105  0.54991959]
 [-0.49519042  0.34740887  0.2467067 ]]
Shat
[2.11185403 0.7915771  0.42181921]
Vhat
[[-0.55614302 -0.58661045 -0.5887216 ]
 [ 0.3180227   0.50425002 -0.80286579]
 [ 0.76783234 -0.63373504 -0.09387969]]
